name: to_do_app_with_cubit_or_bloc
description: "A new Flutter project."
publish_to: 'none' # لمنع النشر على pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  # أيقونات iOS
  cupertino_icons: ^1.0.8

  # Bloc & state management
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.1.1

  # Utilities
  equatable: ^2.0.8
  uuid: ^4.5.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # مثال على إضافة assets (اختياري)
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # مثال على إضافة خطوط (اختياري)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
